# Generated by Django 6.0.2 on 2026-02-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="entity",
            field=models.CharField(
                blank=True,
                help_text="Ex: SERTÃO, ÍNDIA, SOCORROS. Usado no Relatório Geral.",
                max_length=200,
                verbose_name="Entidade/Região",
            ),
        ),
    ]
