# Generated by Django 6.0.5 on 2026-09-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("missions", "0009_alter_adoption_options_alter_investor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialcategory",
            options={
                "ordering": ["type", "order"],
                "verbose_name": "Financial Category",
                "verbose_name_plural": "Financial Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="financialcategory",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="adoption",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="missions.adoption",
                verbose_name="Adoption",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount (R$)"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finance.financialcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=300, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_month",
            field=models.PositiveIntegerField(verbose_name="Reference month"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_year",
            field=models.PositiveIntegerField(verbose_name="Reference year"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
