# Generated by Django 6.0.2 on 2026-02-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_add_entity_to_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="entity",
        ),
    ]
