# Generated by Django 6.0.2 on 2026-02-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("subject", models.CharField(max_length=300, verbose_name="Assunto")),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mensagem de Contato",
                "verbose_name_plural": "Mensagens de Contato",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Pergunta")),
                ("answer", models.TextField(verbose_name="Resposta")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Categoria"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publicada"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pergunta Frequente",
                "verbose_name_plural": "Perguntas Frequentes",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publicada"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Página",
                "verbose_name_plural": "Páginas",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Ex: home_hero, login_side",
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Onde esta imagem é usada",
                        max_length=200,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="Imagem (upload)"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de imagem externa (ex: Unsplash)",
                        verbose_name="URL externa",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Texto alternativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Site",
                "verbose_name_plural": "Imagens do Site",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="Nome do autor"),
                ),
                (
                    "author_role",
                    models.CharField(blank=True, max_length=200, verbose_name="Função"),
                ),
                ("content", models.TextField(verbose_name="Depoimento")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="missions.missionfield",
                        verbose_name="Campo missionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testemunho",
                "verbose_name_plural": "Testemunhos",
                "ordering": ["-created_at"],
            },
        ),
    ]
