# Generated by Django 6.0.5 on 2026-09-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0009_alter_adoption_options_alter_investor_options_and_more"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["category", "order"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["title"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="siteimage",
            options={
                "ordering": ["key"],
                "verbose_name": "Site Image",
                "verbose_name_plural": "Site Images",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=300, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(max_length=100, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=300, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=300, verbose_name="Alt text"),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="description",
            field=models.CharField(
                help_text="Where this image is used",
                max_length=200,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (e.g. Unsplash)",
                verbose_name="External URL",
            ),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="site/", verbose_name="Image (upload)"
            ),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="key",
            field=models.SlugField(
                help_text="E.g.: home_hero, login_side",
                unique=True,
                verbose_name="Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_name",
            field=models.CharField(max_length=200, verbose_name="Author name"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_role",
            field=models.CharField(blank=True, max_length=200, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(verbose_name="Testimonial"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="mission_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="missions.missionfield",
                verbose_name="Mission field",
            ),
        ),
    ]
