# Generated by Django 6.0.2 on 2026-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage_faq_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Ex: home_hero, login_side', unique=True, verbose_name='Identificador')),
                ('description', models.CharField(help_text='Onde esta imagem é usada', max_length=200, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, upload_to='site/', verbose_name='Imagem (upload)')),
                ('external_url', models.URLField(blank=True, help_text='URL de imagem externa (ex: Unsplash)', verbose_name='URL externa')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Texto alternativo')),
            ],
            options={
                'verbose_name': 'Imagem do Site',
                'verbose_name_plural': 'Imagens do Site',
                'ordering': ['key'],
            },
        ),
    ]
