# Generated by Django 6.0.2 on 2026-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionfield',
            name='status',
            field=models.CharField(choices=[('assisted', 'Assistido'), ('unassisted', 'Não assistido')], default='unassisted', max_length=20),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=20),
        ),
    ]
