# Generated by Django 6.0.2 on 2026-02-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionary",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Define se o missionário aparece na listagem pública do site",
                verbose_name="Exibir no site público",
            ),
        ),
    ]
