# Generated by Django 6.0.2 on 2026-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_missionary_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="display_full_name",
            field=models.BooleanField(
                default=True,
                help_text="Se desmarcado, apenas a primeira e última letra do nome serão exibidas no site público",
                verbose_name="Exibir nome completo",
            ),
        ),
    ]
