# Generated by Django 6.0.2 on 2026-02-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_missionfield_status_alter_adoption_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='monthly_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor mensal (R$)'),
        ),
    ]
