# Generated by Django 6.0.2 on 2026-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0003_investor_display_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionfield",
            name="status",
            field=models.CharField(
                choices=[
                    ("assisted", "Assistido"),
                    ("partially_assisted", "Parcialmente assistido"),
                    ("unassisted", "Não assistido"),
                ],
                default="unassisted",
                max_length=20,
            ),
        ),
    ]
