# Generated by Django 6.0.2 on 2026-02-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0004_alter_missionfield_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionfield",
            name="missionaries_needed",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número de missionários necessários para atender este campo",
                verbose_name="Missionários necessários",
            ),
        ),
    ]
