# Generated by Django 6.0.5 on 2026-05-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0005_missionfield_missionaries_needed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="missionary",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Conta de login vinculada a este perfil de missionário",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missionary_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.CreateModel(
            name="MissionFieldRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem opcional do missionário sobre o interesse neste campo",
                        verbose_name="Mensagem",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revisado em"
                    ),
                ),
                (
                    "mission_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="missions.missionfield",
                        verbose_name="Campo Missionário",
                    ),
                ),
                (
                    "missionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_requests",
                        to="missions.missionary",
                        verbose_name="Missionário",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_field_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Campo",
                "verbose_name_plural": "Solicitações de Campos",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("missionary", "mission_field"),
                        name="unique_missionary_field_request",
                    )
                ],
            },
        ),
    ]
