# Generated by Django 6.0.2 on 2026-02-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0005_add_country_to_missionfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="mission_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adoptions",
                to="missions.missionfield",
                verbose_name="Campo Missionário",
            ),
        ),
    ]
