# Generated by Django 6.0.5 on 2026-05-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0006_missionary_user_missionfieldrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Conta de login vinculada a este perfil de investidor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Ativo"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
