# UN member states (193) + 2 observers, in Portuguese.
# Brasil, Índia and Paraguai are placed first for quick access.

COUNTRY_CHOICES = [
    # --- Most used ---
    ("BR", "Brasil"),
    ("IN", "Índia"),
    ("PY", "Paraguai"),
    # --- A ---
    ("AF", "Afeganistão"),
    ("ZA", "África do Sul"),
    ("AL", "Albânia"),
    ("DE", "Alemanha"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AG", "Antígua e Barbuda"),
    ("SA", "Arábia Saudita"),
    ("DZ", "Argélia"),
    ("AR", "Argentina"),
    ("AM", "Armênia"),
    ("AU", "Austrália"),
    ("AT", "Áustria"),
    ("AZ", "Azerbaijão"),
    # --- B ---
    ("BS", "Bahamas"),
    ("BH", "Bahrein"),
    ("BD", "Bangladesh"),
    ("BB", "Barbados"),
    ("BY", "Belarus"),
    ("BE", "Bélgica"),
    ("BZ", "Belize"),
    ("BJ", "Benin"),
    ("BO", "Bolívia"),
    ("BA", "Bósnia e Herzegovina"),
    ("BW", "Botsuana"),
    ("BN", "Brunei"),
    ("BG", "Bulgária"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("BT", "Butão"),
    # --- C ---
    ("CV", "Cabo Verde"),
    ("CM", "Camarões"),
    ("KH", "Camboja"),
    ("CA", "Canadá"),
    ("QA", "Catar"),
    ("KZ", "Cazaquistão"),
    ("TD", "Chade"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CY", "Chipre"),
    ("CO", "Colômbia"),
    ("KM", "Comores"),
    ("CG", "Congo"),
    ("KP", "Coreia do Norte"),
    ("KR", "Coreia do Sul"),
    ("CI", "Costa do Marfim"),
    ("CR", "Costa Rica"),
    ("HR", "Croácia"),
    ("CU", "Cuba"),
    # --- D ---
    ("DK", "Dinamarca"),
    ("DJ", "Djibuti"),
    ("DM", "Dominica"),
    # --- E ---
    ("EG", "Egito"),
    ("SV", "El Salvador"),
    ("AE", "Emirados Árabes Unidos"),
    ("EC", "Equador"),
    ("ER", "Eritreia"),
    ("SK", "Eslováquia"),
    ("SI", "Eslovênia"),
    ("ES", "Espanha"),
    ("US", "Estados Unidos"),
    ("EE", "Estônia"),
    ("SZ", "Eswatini"),
    ("ET", "Etiópia"),
    # --- F ---
    ("FJ", "Fiji"),
    ("PH", "Filipinas"),
    ("FI", "Finlândia"),
    ("FR", "França"),
    # --- G ---
    ("GA", "Gabão"),
    ("GM", "Gâmbia"),
    ("GH", "Gana"),
    ("GE", "Geórgia"),
    ("GD", "Granada"),
    ("GR", "Grécia"),
    ("GT", "Guatemala"),
    ("GY", "Guiana"),
    ("GN", "Guiné"),
    ("GW", "Guiné-Bissau"),
    ("GQ", "Guiné Equatorial"),
    # --- H ---
    ("HT", "Haiti"),
    ("HN", "Honduras"),
    ("HU", "Hungria"),
    # --- I ---
    ("YE", "Iêmen"),
    ("MH", "Ilhas Marshall"),
    ("SB", "Ilhas Salomão"),
    ("ID", "Indonésia"),
    ("IR", "Irã"),
    ("IQ", "Iraque"),
    ("IE", "Irlanda"),
    ("IS", "Islândia"),
    ("IL", "Israel"),
    ("IT", "Itália"),
    # --- J ---
    ("JM", "Jamaica"),
    ("JP", "Japão"),
    ("JO", "Jordânia"),
    # --- K ---
    ("KI", "Quiribati"),
    ("KW", "Kuwait"),
    # --- L ---
    ("LA", "Laos"),
    ("LS", "Lesoto"),
    ("LV", "Letônia"),
    ("LB", "Líbano"),
    ("LR", "Libéria"),
    ("LY", "Líbia"),
    ("LI", "Liechtenstein"),
    ("LT", "Lituânia"),
    ("LU", "Luxemburgo"),
    # --- M ---
    ("MK", "Macedônia do Norte"),
    ("MG", "Madagascar"),
    ("MY", "Malásia"),
    ("MW", "Malauí"),
    ("MV", "Maldivas"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MA", "Marrocos"),
    ("MU", "Maurício"),
    ("MR", "Mauritânia"),
    ("MX", "México"),
    ("FM", "Micronésia"),
    ("MM", "Mianmar"),
    ("MD", "Moldávia"),
    ("MC", "Mônaco"),
    ("MN", "Mongólia"),
    ("ME", "Montenegro"),
    ("MZ", "Moçambique"),
    # --- N ---
    ("NA", "Namíbia"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NI", "Nicarágua"),
    ("NE", "Níger"),
    ("NG", "Nigéria"),
    ("NO", "Noruega"),
    ("NZ", "Nova Zelândia"),
    # --- O ---
    ("OM", "Omã"),
    # --- P ---
    ("NL", "Países Baixos"),
    ("PW", "Palau"),
    ("PS", "Palestina"),
    ("PA", "Panamá"),
    ("PG", "Papua Nova Guiné"),
    ("PK", "Paquistão"),
    ("PE", "Peru"),
    ("PL", "Polônia"),
    ("PT", "Portugal"),
    # --- Q ---
    ("KG", "Quirguistão"),
    # --- R ---
    ("GB", "Reino Unido"),
    ("CF", "República Centro-Africana"),
    ("CD", "República Democrática do Congo"),
    ("DO", "República Dominicana"),
    ("CZ", "República Tcheca"),
    ("RO", "Romênia"),
    ("RW", "Ruanda"),
    ("RU", "Rússia"),
    # --- S ---
    ("WS", "Samoa"),
    ("SM", "San Marino"),
    ("LC", "Santa Lúcia"),
    ("KN", "São Cristóvão e Névis"),
    ("ST", "São Tomé e Príncipe"),
    ("VC", "São Vicente e Granadinas"),
    ("SC", "Seicheles"),
    ("SN", "Senegal"),
    ("SL", "Serra Leoa"),
    ("RS", "Sérvia"),
    ("SG", "Singapura"),
    ("SY", "Síria"),
    ("SO", "Somália"),
    ("LK", "Sri Lanka"),
    ("SD", "Sudão"),
    ("SS", "Sudão do Sul"),
    ("SE", "Suécia"),
    ("CH", "Suíça"),
    ("SR", "Suriname"),
    # --- T ---
    ("TH", "Tailândia"),
    ("TW", "Taiwan"),
    ("TJ", "Tajiquistão"),
    ("TZ", "Tanzânia"),
    ("TL", "Timor-Leste"),
    ("TG", "Togo"),
    ("TO", "Tonga"),
    ("TT", "Trinidad e Tobago"),
    ("TN", "Tunísia"),
    ("TM", "Turcomenistão"),
    ("TR", "Turquia"),
    ("TV", "Tuvalu"),
    # --- U ---
    ("UA", "Ucrânia"),
    ("UG", "Uganda"),
    ("UY", "Uruguai"),
    ("UZ", "Uzbequistão"),
    # --- V ---
    ("VU", "Vanuatu"),
    ("VA", "Vaticano"),
    ("VE", "Venezuela"),
    ("VN", "Vietnã"),
    # --- Z ---
    ("ZM", "Zâmbia"),
    ("ZW", "Zimbábue"),
]
